def fifty_shades():
    word_1 = str(input('Enter a verb ending in s: '))
    word_2 = str(input('Enter a body part: '))
    word_3 = str(input('Enter a body part: '))
    word_4 = str(input('Enter a body part: '))
    word_5 = str(input('Enter a verb ending in s: '))
    word_6 = str(input('Enter a body part: '))
    word_7 = str(input('Enter a body part: '))
    word_8 = str(input('Enter a verb ending in s: '))
    word_9 = str(input('Enter an adjective: '))
    word_10 = str(input('Enter an adjective: '))
    word_11 = str(input('Enter a body part: '))
    word_12 = str(input('Enter a body part: '))
    word_13 = str(input('Enter a body part: '))
    word_14 = str(input('Enter a body part: '))
    word_15 = str(input('Enter your name: '))
    word_16 = str(input('Enter a verb ending in s: '))
    word_17 = str(input('Enter a noun: '))
    word_18 = str(input('Enter a body part: '))
    word_19 = str(input('Enter a noun: '))
    word_20 = str(input('Enter a body part: '))
    word_21 = str(input('Enter a body part: '))
    word_22 = str(input('Enter a body part: '))
    word_23 = str(input('Enter an adverb: '))
    word_24 = str(input('Enter an adjective: '))
    word_25 = str(input('Enter a noun: '))
    word_26 = str(input("Enter someone's name: "))
    word_27 = str(input('Enter an adjective: '))
    word_28 = str(input('Enter an adjective: '))
    word_29 = str(input('Enter a verb ending in ing: '))
    fifty_shades_of_python = f'He {word_1} his {word_2} so his {word_4} pushes against me. “Yes...right there…”. He {word_5} his {word_6} along my {word_7}, eases back, then {word_8} into me again--so {word_9}, so {word_10}, --his {word_11} pressing down on me, his {word_12} and his {word_13} on either side of my {word_14}. “Oh, {word_15},” he {word_16} as he lets go, my name a {word_17} on his {word_18} as he finds his {word_19}. His {word_20} rests on my {word_21}, his {word_22} wrapped around me… I just want to enjoy the {word_23} {word_24} afterglow of making {word_25} with {word_26}, because that’s what we’ve done: {word_27} {word_28} {word_29}.'
    print(fifty_shades_of_python)

def awkward_encounter():
    word_1 = str(input('Enter a verb ending in ing: '))
    word_2 = str(input('Enter a type of liquid: '))
    word_3 = str(input('Enter a type of food: '))
    word_4 = str(input('Enter an adjective: '))
    word_5 = str(input('Enter a noun: '))
    word_6 = str(input('Enter an adverb: '))
    word_7 = str(input('Enter a noun: '))
    word_8 = str(input('Enter an adjective: '))
    word_9 = str(input('Enter a verb: '))
    word_10 = str(input('Enter an adverb: '))
    word_11 = str(input('Enter a plural noun: '))
    word_12 = str(input('Enter a plural noun: '))
    word_13 = str(input('Enter a body part: '))
    word_14 = str(input('Enter a plural noun: '))
    word_15 = str(input('Enter an adjective: '))
    word_16 = str(input("Enter some one's name: "))
    word_17 = str(input('Enter a exclamation: '))
    word_18 = str(input('Enter a place: '))
    awkward_story = f"After {word_1} shotguns at the range, drinking {word_2} by the pool, and a big {word_3} dinner, this is turning out to be a/an {word_4} night. I’m at some bar called the {word_5} Lounge, and I am {word_6} smashed right now. We have {word_7} service in a/an {word_8} VIP area, but there are no girls here. Well, I’m the groom, so I think I’ll go {word_9} some up. I can’t {word_10} see anything with all the flashing {word_11} in this club, but I think there’s a group of {word_12} in that corner. Hmmm... there’s a brunette over there...I can’t see her face, but boy does she have a great {word_13}. I’ll ask her if she and her friends want to join us for a round of {word_14}. ‘Excuse me, but we have {word_15} booze and no one to share it with. Want to join us?’ I ask. She turns around and smiles at me. ‘Yes, {word_16}, we’d love to join you,’ she replies. {word_17}! I must be the only groom in (the) {word_18} to hit on his own fiancee during his bachelor party."
    print(awkward_story)

def asking_out():
    word_1 = str(input('Enter a term of endearment: '))
    word_2 = str(input('Enter a first name: '))
    word_3 = str(input('Enter a last name: '))
    word_4 = str(input('Enter a place: '))
    word_5 = str(input('Enter a plural unit of time: '))
    word_6 = str(input('Enter an adjective: '))
    word_7 = str(input('Enter a color: '))
    word_8 = str(input('Enter an item of clothing: '))
    word_9 = str(input('Enter a number: '))
    word_10 = str(input('Enter a verb: '))
    word_11 = str(input('Enter a verb: '))
    word_12 = str(input('Enter a verb: '))
    word_13 = str(input('Enter a verb: '))
    proposition = f"Hey, {word_1}. It’s me. What’s up? You know, {word_2}. {word_2} {word_3}. From the {word_4}. Two {word_5} ago. I was the {word_6} guy in the {word_7} parachute {word_8}. I paid the bus boy {word_9} dollars to {word_10} me your information. I was wondering if maybe you’d like to {word_11} out with me. Please don’t call the {word_12} department. Alright, I’ll {word_13}. So, that’s a no, right?"
    print(proposition)

def restroom_recon():
    word_1 = str(input('Enter an adjective: '))
    word_2 = str(input('Enter an adverb: '))
    word_3 = str(input('Enter a noun: '))
    word_4 = str(input('Enter an adverb: '))
    word_5 = str(input('Enter an adjective: '))
    word_6 = str(input('Enter a place: '))
    word_7 = str(input('Enter a noun: '))
    word_8 = str(input('Enter a body part: '))
    word_9 = str(input('Enter an adjective: '))
    word_10 = str(input('Enter a noun: '))
    word_11 = str(input('Enter an adjective: '))
    word_12 = str(input('Enter a number: '))
    word_13 = str(input('Enter an adverb: '))
    word_14 = str(input('Enter an adjective: '))
    word_15 = str(input('Enter a noun: '))
    restroom = f"Ladies, you are two of the smartest, most {word_1} women in this entire office, and I have come to you today because I need your help. I’ll be {word_2} honest: I have to take a big {word_3} in the bathroom, and I need to find a stall with a strong Wi-Fi signal. I mean, data plans are {word_4} expensive and, without being too specific, I’m going to be in there for a very, very {word_5} time. I had the lunch special at Cafe el {word_6} and it’s like a ticking time {word_7} in my {word_8}, if you know what I mean. Anyway, since they removed the {word_9} magazines from the men’s bathroom, I have a difficult time concentrating on the {word_10} at hand. The women’s restroom is right next door. So if you don’t mind, go in, check out the Wi-Fi, and tell me which area has the most {word_11} signal. I would do it myself, but once I sit down, I’m committed for at least {word_12} minutes. We can’t be {word_13} obvious about this, though, so be {word_14}. Got it? Good. Now, please hurry. The turtle is starting to poke his head out of his {word_15}, if you know what I mean."
    print(restroom)


def job_interview():
    word_1 = str(input('Enter an article of clothing: '))
    word_2 = str(input('Enter a superlative: '))
    word_3 = str(input('Enter a plural noun: '))
    word_4 = str(input('Enter a sport: '))
    word_5 = str(input('Enter a noun: '))
    word_6 = str(input('Enter a personal title: '))
    word_7 = str(input('Enter a adverb: '))
    word_8 = str(input('Enter an proper noun: '))
    word_9 = str(input('Enter a song title: '))
    word_10 = str(input('Enter an interjection: '))
    word_11 = str(input('Enter an article of clothing: '))
    word_12 = str(input('Enter a verb: '))
    word_13 = str(input('Enter a name: '))
    word_14 = str(input('Enter a plural noun: '))
    word_15 = str(input('Enter an plural noun: '))
    word_16 = str(input("Enter an article of clothing: "))
    word_17 = str(input('Enter an adjective: '))
    word_18 = str(input('Enter a field of study: '))
    job = f"I scoured my closet for the perfect {word_1} to wear. Dressing for the {word_2} place around isn’t easy. Sweating {word_3} during the interview is a sure sign of weakness. I must remember to play up my strengths: {word_4}, menacing stares, and {word_5} collecting. It has always been my dream to work with the Angel of Death, or {word_6} Devil. The power and prestige are {word_7} desirable. The Gates of {word_8} tower above me as I ring the doorbell. I can’t believe {word_9} is the doorbell chime. {word_10}, his black {word_11} looks better in person! ‘Welcome to Hell. Your interview will {word_12} now.’ ‘It’s a pleasure to meet you. My name is {word_13}.’ ‘Who cares? I only have one question. Do you hate {word_14}?’ ‘Yes, yes I do. I hate them more than {word_15}.’ ‘You’re hired. Wait, is that a {word_16} you’re wearing?’ ‘No, it’s actually a {word_17} suit.’ ‘You’re fired. Maybe you should pursue a career in {word_18}.’"
    print(job)

def giraffe_facts():
    word_1 = str(input('Enter an  plural noun: '))
    word_2 = str(input('Enter a plural noun: '))
    word_3 = str(input('Enter a body part: '))
    word_4 = str(input('Enter a number: '))
    word_5 = str(input('Enter a plural noun: '))
    word_6 = str(input('Enter a body part: '))
    word_7 = str(input('Enter a liquid: '))
    word_8 = str(input('Enter a plural body part: '))
    word_9 = str(input('Enter a body part: '))
    word_10 = str(input('Enter an adjective: '))
    word_11 = str(input('Enter a plural noun: '))
    word_12 = str(input('Enter an adjective: '))
    word_13 = str(input('Enter an adjective: '))
    word_14 = str(input('Enter a verb ending in ing: '))
    word_15 = str(input('Enter a noun: '))
    word_16 = str(input("Enter a verb:"))
    word_17 = str(input('Enter a noun: '))
    giraffe = f"Giraffes have aroused the curiosity of {word_1} since earliest times. The giraffe is the tallest of all living {word_2}, but scientists are unable to explain how it got its long {word_3}. The giraffe’s tremendous height, which might reach {word_4} {word_5}, comes mostly from its legs and {word_6}. If the giraffe wants to take a drink of {word_7} from the ground, it has to spread its {word_8} far apart in order to reach down and lap up the water with its huge {word_9}. The giraffe has {word_10} ears that are sensitive to the faintest {word_11}, and it has a/an {word_12} sense of smell and sight. When attacked, a giraffe can put up a/an {word_13} fight by {word_14} out with its hind legs and using its head like a sledge {word_15}. Finally, a giraffe can {word_16} at more than thirty miles an hour when pursued and can outrun the fastest {word_17}."
    print(giraffe)